### ISSUE TITLE
Automatic synchronization when modifying a file in the directory

### ISSUE THREAD

**Issue by Tapyu** [liberodark/ODrive#119]
I was able to synchronize the google drive in my "Folder Location", but any change in this directory isn't automatically sync whit the GoogleDrive.

1. I create a text document (6Kbs) in the File Location synchronization.
2. This file isn't appear in my Google Drive automatically.

There are any option in the Odrive to make this Automatic synchronization?

OBS: I'm newbie, so take easy, please :)

**Comment by kasi-mir33** [comment]
Same issue here. 

I synchronized my Google Drive folder. Since most of the data was already on this laptop it was ignored and not re-downloaded (good feature) but unfortunately, the new data wasn't synched with the online G-Drive folder. 

@liberodark Is there any way to force an upload and not just a download?

**Comment by andressalazar08** [comment]
Good Day,
I got the same issue, it doesnt sync from my files back to google drive.
is there a solution?
thanks
