### ISSUE TITLE
Add support for Flatpak packages

### ISSUE THREAD

**Issue by LeandroStanger** [liberodark/ODrive#40]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by x80486** [comment]
I did the initial work for this [here](https://github.com/x80486/flathub/tree/io.github.liberodark.OpenDrive/).

It's based on the `.deb` file because I couldn't build it using what's specified in `package.json`. I'll give it another whirl some time later to see if I can get it done in such a way...but this is functional as it's right now.

So, @liberodark, would you like to get involved in this one? It's basically updating from time to time the JSON manifest; if not, I can do it for the time being.

Moreover, I think it would be great if you can:

- Check the AppData XML file – the same provides descriptive data about the application, and is typically used in application managers to display additional information to the user
- Check if the application ID I'm using is correct (although I guess there is an Issue reported that maybe changes that)
- Generate the icon(s) as `app-id.desktop`; e.g.: `io.github.liberodark.OpenDrive.desktop`. That's a good to have.

**Comment by LeandroStanger** [comment]
https://flathub.org/apps/details/io.github.liberodark.OpenDrive
